//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.10 at 05:22:11 PM JST 
//


package bms.player.lunaticrave2.ir;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}hash"/>
 *         &lt;element ref="{}clear"/>
 *         &lt;element ref="{}notes"/>
 *         &lt;element ref="{}combo"/>
 *         &lt;element ref="{}pg"/>
 *         &lt;element ref="{}gr"/>
 *         &lt;element ref="{}gd"/>
 *         &lt;element ref="{}bd"/>
 *         &lt;element ref="{}pr"/>
 *         &lt;element ref="{}minbp"/>
 *         &lt;element ref="{}option"/>
 *         &lt;element ref="{}lastupdate"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "hash",
    "clear",
    "notes",
    "combo",
    "pg",
    "gr",
    "gd",
    "bd",
    "pr",
    "minbp",
    "option",
    "lastupdate"
})
@XmlRootElement(name = "score")
public class Score {

    @XmlElement(required = true)
    protected String hash;
    @XmlElement(required = true)
    protected BigInteger clear;
    @XmlElement(required = true)
    protected BigInteger notes;
    @XmlElement(required = true)
    protected BigInteger combo;
    @XmlElement(required = true)
    protected BigInteger pg;
    @XmlElement(required = true)
    protected BigInteger gr;
    @XmlElement(required = true)
    protected BigInteger gd;
    @XmlElement(required = true)
    protected BigInteger bd;
    @XmlElement(required = true)
    protected BigInteger pr;
    @XmlElement(required = true)
    protected BigInteger minbp;
    @XmlElement(required = true)
    protected BigInteger option;
    @XmlElement(required = true)
    protected BigInteger lastupdate;

    /**
     * Gets the value of the hash property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHash() {
        return hash;
    }

    /**
     * Sets the value of the hash property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHash(String value) {
        this.hash = value;
    }

    /**
     * Gets the value of the clear property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getClear() {
        return clear;
    }

    /**
     * Sets the value of the clear property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setClear(BigInteger value) {
        this.clear = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNotes(BigInteger value) {
        this.notes = value;
    }

    /**
     * Gets the value of the combo property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCombo() {
        return combo;
    }

    /**
     * Sets the value of the combo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCombo(BigInteger value) {
        this.combo = value;
    }

    /**
     * Gets the value of the pg property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPg() {
        return pg;
    }

    /**
     * Sets the value of the pg property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPg(BigInteger value) {
        this.pg = value;
    }

    /**
     * Gets the value of the gr property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGr() {
        return gr;
    }

    /**
     * Sets the value of the gr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGr(BigInteger value) {
        this.gr = value;
    }

    /**
     * Gets the value of the gd property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGd() {
        return gd;
    }

    /**
     * Sets the value of the gd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGd(BigInteger value) {
        this.gd = value;
    }

    /**
     * Gets the value of the bd property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBd() {
        return bd;
    }

    /**
     * Sets the value of the bd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBd(BigInteger value) {
        this.bd = value;
    }

    /**
     * Gets the value of the pr property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPr() {
        return pr;
    }

    /**
     * Sets the value of the pr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPr(BigInteger value) {
        this.pr = value;
    }

    /**
     * Gets the value of the minbp property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMinbp() {
        return minbp;
    }

    /**
     * Sets the value of the minbp property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMinbp(BigInteger value) {
        this.minbp = value;
    }

    /**
     * Gets the value of the option property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOption() {
        return option;
    }

    /**
     * Sets the value of the option property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOption(BigInteger value) {
        this.option = value;
    }

    /**
     * Gets the value of the lastupdate property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLastupdate() {
        return lastupdate;
    }

    /**
     * Sets the value of the lastupdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLastupdate(BigInteger value) {
        this.lastupdate = value;
    }

}
