//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.12 at 11:34:54 AM JST 
//


package bms.player.lunaticrave2.config;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}lr1ir"/>
 *         &lt;element ref="{}lr1id"/>
 *         &lt;element ref="{}lr1pass"/>
 *         &lt;element ref="{}lr2ir"/>
 *         &lt;element ref="{}mail"/>
 *         &lt;element ref="{}autoupdate"/>
 *         &lt;element ref="{}getrival"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "lr1Ir",
    "lr1Id",
    "lr1Pass",
    "lr2Ir",
    "mail",
    "autoupdate",
    "getrival"
})
@XmlRootElement(name = "network")
public class Network {

    @XmlElement(name = "lr1ir", required = true)
    protected BigInteger lr1Ir;
    @XmlElement(name = "lr1id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String lr1Id;
    @XmlElement(name = "lr1pass", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String lr1Pass;
    @XmlElement(name = "lr2ir", required = true)
    protected BigInteger lr2Ir;
    @XmlElement(required = true)
    protected Mail mail;
    @XmlElement(required = true)
    protected BigInteger autoupdate;
    @XmlElement(required = true)
    protected BigInteger getrival;

    /**
     * Gets the value of the lr1Ir property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLr1Ir() {
        return lr1Ir;
    }

    /**
     * Sets the value of the lr1Ir property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLr1Ir(BigInteger value) {
        this.lr1Ir = value;
    }

    /**
     * Gets the value of the lr1Id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLr1Id() {
        return lr1Id;
    }

    /**
     * Sets the value of the lr1Id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLr1Id(String value) {
        this.lr1Id = value;
    }

    /**
     * Gets the value of the lr1Pass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLr1Pass() {
        return lr1Pass;
    }

    /**
     * Sets the value of the lr1Pass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLr1Pass(String value) {
        this.lr1Pass = value;
    }

    /**
     * Gets the value of the lr2Ir property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLr2Ir() {
        return lr2Ir;
    }

    /**
     * Sets the value of the lr2Ir property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLr2Ir(BigInteger value) {
        this.lr2Ir = value;
    }

    /**
     * Gets the value of the mail property.
     * 
     * @return
     *     possible object is
     *     {@link Mail }
     *     
     */
    public Mail getMail() {
        return mail;
    }

    /**
     * Sets the value of the mail property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mail }
     *     
     */
    public void setMail(Mail value) {
        this.mail = value;
    }

    /**
     * Gets the value of the autoupdate property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAutoupdate() {
        return autoupdate;
    }

    /**
     * Sets the value of the autoupdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAutoupdate(BigInteger value) {
        this.autoupdate = value;
    }

    /**
     * Gets the value of the getrival property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGetrival() {
        return getrival;
    }

    /**
     * Sets the value of the getrival property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGetrival(BigInteger value) {
        this.getrival = value;
    }

}
