//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.12 at 11:34:54 AM JST 
//


package bms.player.lunaticrave2.config;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the bms.lr2.config package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Outputlog_QNAME = new QName("", "outputlog");
    private final static QName _Levelbarflash9_QNAME = new QName("", "levelbarflash_9");
    private final static QName _Levelbarflash7_QNAME = new QName("", "levelbarflash_7");
    private final static QName _Folderlamp_QNAME = new QName("", "folderlamp");
    private final static QName _Levelbarflash5_QNAME = new QName("", "levelbarflash_5");
    private final static QName _Hstype_QNAME = new QName("", "hstype");
    private final static QName _Replaysave_QNAME = new QName("", "replaysave");
    private final static QName _Ghost_QNAME = new QName("", "ghost");
    private final static QName _Autoscratch_QNAME = new QName("", "autoscratch");
    private final static QName _Maxlevel_QNAME = new QName("", "maxlevel");
    private final static QName _Fxtarget2_QNAME = new QName("", "fxtarget_2");
    private final static QName _Fxtarget1_QNAME = new QName("", "fxtarget_1");
    private final static QName _Fxtarget0_QNAME = new QName("", "fxtarget_0");
    private final static QName _Pitchflag_QNAME = new QName("", "pitchflag");
    private final static QName _Volumekey_QNAME = new QName("", "volumekey");
    private final static QName _Thread_QNAME = new QName("", "thread");
    private final static QName _Autojudgeadjust_QNAME = new QName("", "autojudgeadjust");
    private final static QName _Ignoredifficultyall_QNAME = new QName("", "ignoredifficultyall");
    private final static QName _Minlevel_QNAME = new QName("", "minlevel");
    private final static QName _Disablesubtitle_QNAME = new QName("", "disablesubtitle");
    private final static QName _Poorbga_QNAME = new QName("", "poorbga");
    private final static QName _Autowavtoogg_QNAME = new QName("", "autowavtoogg");
    private final static QName _Bgasize_QNAME = new QName("", "bgasize");
    private final static QName _Mp3EncOptionMovie_QNAME = new QName("", "mp3enc_option_movie");
    private final static QName _Play14_QNAME = new QName("", "play_14");
    private final static QName _Lr1Ir_QNAME = new QName("", "lr1ir");
    private final static QName _Softwarerendering_QNAME = new QName("", "softwarerendering");
    private final static QName _Play10_QNAME = new QName("", "play_10");
    private final static QName _Random_QNAME = new QName("", "random");
    private final static QName _Autoupdate_QNAME = new QName("", "autoupdate");
    private final static QName _Lr2Ir_QNAME = new QName("", "lr2ir");
    private final static QName _Maindisplay_QNAME = new QName("", "maindisplay");
    private final static QName _Mainsleep_QNAME = new QName("", "mainsleep");
    private final static QName _Bmssleep_QNAME = new QName("", "bmssleep");
    private final static QName _Defaultgauge_QNAME = new QName("", "defaultgauge");
    private final static QName _Defaultconnection_QNAME = new QName("", "defaultconnection");
    private final static QName _Preview_QNAME = new QName("", "preview");
    private final static QName _Eventmode_QNAME = new QName("", "eventmode");
    private final static QName _Soundset_QNAME = new QName("", "soundset");
    private final static QName _Disablebmsthread_QNAME = new QName("", "disablebmsthread");
    private final static QName _Lr1Id_QNAME = new QName("", "lr1id");
    private final static QName _Bpmrange_QNAME = new QName("", "bpmrange");
    private final static QName _Speedfirst_QNAME = new QName("", "speedfirst");
    private final static QName _MovieFramerate_QNAME = new QName("", "movie_framerate");
    private final static QName _Language_QNAME = new QName("", "language");
    private final static QName _Sort_QNAME = new QName("", "sort");
    private final static QName _Searchmax_QNAME = new QName("", "searchmax");
    private final static QName _Autokey_QNAME = new QName("", "autokey");
    private final static QName _OggencOption_QNAME = new QName("", "oggenc_option");
    private final static QName _Shuttertype_QNAME = new QName("", "shuttertype");
    private final static QName _Optimumlevel5_QNAME = new QName("", "optimumlevel_5");
    private final static QName _Ignorekeysingle_QNAME = new QName("", "ignorekeysingle");
    private final static QName _Optimumlevel9_QNAME = new QName("", "optimumlevel_9");
    private final static QName _Fxtype0_QNAME = new QName("", "fxtype_0");
    private final static QName _Fxtype1_QNAME = new QName("", "fxtype_1");
    private final static QName _Fxtype2_QNAME = new QName("", "fxtype_2");
    private final static QName _Optimumlevel7_QNAME = new QName("", "optimumlevel_7");
    private final static QName _Disablecurspeedchange_QNAME = new QName("", "disablecurspeedchange");
    private final static QName _Defaulttarget_QNAME = new QName("", "defaulttarget");
    private final static QName _Fxflag0_QNAME = new QName("", "fxflag_0");
    private final static QName _Eqp4_QNAME = new QName("", "eqp4");
    private final static QName _Eqp5_QNAME = new QName("", "eqp5");
    private final static QName _Skinselect_QNAME = new QName("", "skinselect");
    private final static QName _Eqp6_QNAME = new QName("", "eqp6");
    private final static QName _Disabledsp_QNAME = new QName("", "disabledsp");
    private final static QName _Fxp12_QNAME = new QName("", "fxp1_2");
    private final static QName _Hsmargin_QNAME = new QName("", "hsmargin");
    private final static QName _Fxp11_QNAME = new QName("", "fxp1_1");
    private final static QName _Fxp10_QNAME = new QName("", "fxp1_0");
    private final static QName _Screenmode_QNAME = new QName("", "screenmode");
    private final static QName _Gomiscore_QNAME = new QName("", "gomiscore");
    private final static QName _Highcolor_QNAME = new QName("", "highcolor");
    private final static QName _Scoregraph_QNAME = new QName("", "scoregraph");
    private final static QName _Eqp1_QNAME = new QName("", "eqp1");
    private final static QName _Eqp0_QNAME = new QName("", "eqp0");
    private final static QName _Eqp3_QNAME = new QName("", "eqp3");
    private final static QName _Eqp2_QNAME = new QName("", "eqp2");
    private final static QName _Keyconfig_QNAME = new QName("", "keyconfig");
    private final static QName _Fxflag1_QNAME = new QName("", "fxflag_1");
    private final static QName _Fxflag2_QNAME = new QName("", "fxflag_2");
    private final static QName _Autoreload_QNAME = new QName("", "autoreload");
    private final static QName _Mp3EncOptionNormal_QNAME = new QName("", "mp3enc_option_normal");
    private final static QName _Disablesystemkey_QNAME = new QName("", "disablesystemkey");
    private final static QName _Speednext_QNAME = new QName("", "speednext");
    private final static QName _Pitchtype_QNAME = new QName("", "pitchtype");
    private final static QName _Randomclose_QNAME = new QName("", "randomclose");
    private final static QName _Mp3Volume_QNAME = new QName("", "mp3_volume");
    private final static QName _Optimumlevel14_QNAME = new QName("", "optimumlevel_14");
    private final static QName _Disableleftclickexit_QNAME = new QName("", "disableleftclickexit");
    private final static QName _Getrival_QNAME = new QName("", "getrival");
    private final static QName _Difficulty_QNAME = new QName("", "difficulty");
    private final static QName _Disablefolderthread_QNAME = new QName("", "disablefolderthread");
    private final static QName _Optimumlevel10_QNAME = new QName("", "optimumlevel_10");
    private final static QName _Customfolder_QNAME = new QName("", "customfolder");
    private final static QName _Ignoredp_QNAME = new QName("", "ignoredp");
    private final static QName _Ignorekeyall_QNAME = new QName("", "ignorekeyall");
    private final static QName _Bga_QNAME = new QName("", "bga");
    private final static QName _Key_QNAME = new QName("", "key");
    private final static QName _Control_QNAME = new QName("", "control");
    private final static QName _Maxbpm_QNAME = new QName("", "maxbpm");
    private final static QName _Bufferlength_QNAME = new QName("", "bufferlength");
    private final static QName _Ignorepms_QNAME = new QName("", "ignorepms");
    private final static QName _Judgetime_QNAME = new QName("", "judgetime");
    private final static QName _Numbuffers_QNAME = new QName("", "numbuffers");
    private final static QName _Disabledifficultyfilter_QNAME = new QName("", "disabledifficultyfilter");
    private final static QName _Vsync_QNAME = new QName("", "vsync");
    private final static QName _Screenexrate_QNAME = new QName("", "screenexrate");
    private final static QName _Shuttermargin_QNAME = new QName("", "shuttermargin");
    private final static QName _OggencBody_QNAME = new QName("", "oggenc_body");
    private final static QName _Play7B_QNAME = new QName("", "play_7_b");
    private final static QName _Shutter_QNAME = new QName("", "shutter");
    private final static QName _Play5_QNAME = new QName("", "play_5");
    private final static QName _Output_QNAME = new QName("", "output");
    private final static QName _Play9_QNAME = new QName("", "play_9");
    private final static QName _Play5B_QNAME = new QName("", "play_5_b");
    private final static QName _Play7_QNAME = new QName("", "play_7");
    private final static QName _Ignorekeydouble_QNAME = new QName("", "ignorekeydouble");
    private final static QName _Result_QNAME = new QName("", "result");
    private final static QName _Decide_QNAME = new QName("", "decide");
    private final static QName _Hs_QNAME = new QName("", "hs");
    private final static QName _BmseBody_QNAME = new QName("", "bmse_body");
    private final static QName _Volumeflag_QNAME = new QName("", "volumeflag");
    private final static QName _Basespeed_QNAME = new QName("", "basespeed");
    private final static QName _Volumebgm_QNAME = new QName("", "volumebgm");
    private final static QName _MovieAudio_QNAME = new QName("", "movie_audio");
    private final static QName _Disableimagefont_QNAME = new QName("", "disableimagefont");
    private final static QName _Stage_QNAME = new QName("", "stage");
    private final static QName _Disablefmod_QNAME = new QName("", "disablefmod");
    private final static QName _Id_QNAME = new QName("", "id");
    private final static QName _Pitchp_QNAME = new QName("", "pitchp");
    private final static QName _Autobmptopng_QNAME = new QName("", "autobmptopng");
    private final static QName _WindowsizeY_QNAME = new QName("", "windowsize_y");
    private final static QName _Path_QNAME = new QName("", "path");
    private final static QName _WindowsizeX_QNAME = new QName("", "windowsize_x");
    private final static QName _Eqflag_QNAME = new QName("", "eqflag");
    private final static QName _Driver_QNAME = new QName("", "driver");
    private final static QName _Mp3EncBody_QNAME = new QName("", "mp3enc_body");
    private final static QName _Autofumensearch_QNAME = new QName("", "autofumensearch");
    private final static QName _Newsongfolder_QNAME = new QName("", "newsongfolder");
    private final static QName _Lr1Pass_QNAME = new QName("", "lr1pass");
    private final static QName _Inputinterval_QNAME = new QName("", "inputinterval");
    private final static QName _Fontname_QNAME = new QName("", "fontname");
    private final static QName _Pass_QNAME = new QName("", "pass");
    private final static QName _Titleflash_QNAME = new QName("", "titleflash");
    private final static QName _Hsmax_QNAME = new QName("", "hsmax");
    private final static QName _Volumemaster_QNAME = new QName("", "volumemaster");
    private final static QName _Buttonselect_QNAME = new QName("", "buttonselect");
    private final static QName _Minbpm_QNAME = new QName("", "minbpm");
    private final static QName _Ignore5Key_QNAME = new QName("", "ignore5key");
    private final static QName _Effect_QNAME = new QName("", "effect");
    private final static QName _Difficultychangetype_QNAME = new QName("", "difficultychangetype");
    private final static QName _Hptimer_QNAME = new QName("", "hptimer");
    private final static QName _Directdraw_QNAME = new QName("", "directdraw");
    private final static QName _Gauge_QNAME = new QName("", "gauge");
    private final static QName _Target_QNAME = new QName("", "target");
    private final static QName _Fxp20_QNAME = new QName("", "fxp2_0");
    private final static QName _Fxp21_QNAME = new QName("", "fxp2_1");
    private final static QName _Disableskinpreview_QNAME = new QName("", "disableskinpreview");
    private final static QName _Fxp22_QNAME = new QName("", "fxp2_2");
    private final static QName _Hsmin_QNAME = new QName("", "hsmin");
    private final static QName _OggdecBody_QNAME = new QName("", "oggdec_body");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: bms.lr2.config
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Course }
     * 
     */
    public Course createCourse() {
        return new Course();
    }

    /**
     * Create an instance of {@link Config }
     * 
     */
    public Config createConfig() {
        return new Config();
    }

    /**
     * Create an instance of {@link System }
     * 
     */
    public System createSystem() {
        return new System();
    }

    /**
     * Create an instance of {@link Jukebox }
     * 
     */
    public Jukebox createJukebox() {
        return new Jukebox();
    }

    /**
     * Create an instance of {@link Play }
     * 
     */
    public Play createPlay() {
        return new Play();
    }

    /**
     * Create an instance of {@link Sound }
     * 
     */
    public Sound createSound() {
        return new Sound();
    }

    /**
     * Create an instance of {@link Player }
     * 
     */
    public Player createPlayer() {
        return new Player();
    }

    /**
     * Create an instance of {@link Name }
     * 
     */
    public Name createName() {
        return new Name();
    }

    /**
     * Create an instance of {@link Irid }
     * 
     */
    public Irid createIrid() {
        return new Irid();
    }

    /**
     * Create an instance of {@link Irpass }
     * 
     */
    public Irpass createIrpass() {
        return new Irpass();
    }

    /**
     * Create an instance of {@link Select }
     * 
     */
    public Select createSelect() {
        return new Select();
    }

    /**
     * Create an instance of {@link Skin }
     * 
     */
    public Skin createSkin() {
        return new Skin();
    }

    /**
     * Create an instance of {@link Theme }
     * 
     */
    public Theme createTheme() {
        return new Theme();
    }

    /**
     * Create an instance of {@link Play9B }
     * 
     */
    public Play9B createPlay9B() {
        return new Play9B();
    }

    /**
     * Create an instance of {@link Network }
     * 
     */
    public Network createNetwork() {
        return new Network();
    }

    /**
     * Create an instance of {@link Mail }
     * 
     */
    public Mail createMail() {
        return new Mail();
    }

    /**
     * Create an instance of {@link Tools }
     * 
     */
    public Tools createTools() {
        return new Tools();
    }

    /**
     * Create an instance of {@link BmseOption }
     * 
     */
    public BmseOption createBmseOption() {
        return new BmseOption();
    }

    /**
     * Create an instance of {@link OggdecOption }
     * 
     */
    public OggdecOption createOggdecOption() {
        return new OggdecOption();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "outputlog")
    public JAXBElement<BigInteger> createOutputlog(BigInteger value) {
        return new JAXBElement<BigInteger>(_Outputlog_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "levelbarflash_9")
    public JAXBElement<BigInteger> createLevelbarflash9(BigInteger value) {
        return new JAXBElement<BigInteger>(_Levelbarflash9_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "levelbarflash_7")
    public JAXBElement<BigInteger> createLevelbarflash7(BigInteger value) {
        return new JAXBElement<BigInteger>(_Levelbarflash7_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "folderlamp")
    public JAXBElement<BigInteger> createFolderlamp(BigInteger value) {
        return new JAXBElement<BigInteger>(_Folderlamp_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "levelbarflash_5")
    public JAXBElement<BigInteger> createLevelbarflash5(BigInteger value) {
        return new JAXBElement<BigInteger>(_Levelbarflash5_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "hstype")
    public JAXBElement<BigInteger> createHstype(BigInteger value) {
        return new JAXBElement<BigInteger>(_Hstype_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "replaysave")
    public JAXBElement<BigInteger> createReplaysave(BigInteger value) {
        return new JAXBElement<BigInteger>(_Replaysave_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ghost")
    public JAXBElement<BigInteger> createGhost(BigInteger value) {
        return new JAXBElement<BigInteger>(_Ghost_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "autoscratch")
    public JAXBElement<BigInteger> createAutoscratch(BigInteger value) {
        return new JAXBElement<BigInteger>(_Autoscratch_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "maxlevel")
    public JAXBElement<BigInteger> createMaxlevel(BigInteger value) {
        return new JAXBElement<BigInteger>(_Maxlevel_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fxtarget_2")
    public JAXBElement<BigInteger> createFxtarget2(BigInteger value) {
        return new JAXBElement<BigInteger>(_Fxtarget2_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fxtarget_1")
    public JAXBElement<BigInteger> createFxtarget1(BigInteger value) {
        return new JAXBElement<BigInteger>(_Fxtarget1_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fxtarget_0")
    public JAXBElement<BigInteger> createFxtarget0(BigInteger value) {
        return new JAXBElement<BigInteger>(_Fxtarget0_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pitchflag")
    public JAXBElement<BigInteger> createPitchflag(BigInteger value) {
        return new JAXBElement<BigInteger>(_Pitchflag_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "volumekey")
    public JAXBElement<BigInteger> createVolumekey(BigInteger value) {
        return new JAXBElement<BigInteger>(_Volumekey_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "thread")
    public JAXBElement<BigInteger> createThread(BigInteger value) {
        return new JAXBElement<BigInteger>(_Thread_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "autojudgeadjust")
    public JAXBElement<BigInteger> createAutojudgeadjust(BigInteger value) {
        return new JAXBElement<BigInteger>(_Autojudgeadjust_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ignoredifficultyall")
    public JAXBElement<BigInteger> createIgnoredifficultyall(BigInteger value) {
        return new JAXBElement<BigInteger>(_Ignoredifficultyall_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "minlevel")
    public JAXBElement<BigInteger> createMinlevel(BigInteger value) {
        return new JAXBElement<BigInteger>(_Minlevel_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "disablesubtitle")
    public JAXBElement<BigInteger> createDisablesubtitle(BigInteger value) {
        return new JAXBElement<BigInteger>(_Disablesubtitle_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "poorbga")
    public JAXBElement<BigInteger> createPoorbga(BigInteger value) {
        return new JAXBElement<BigInteger>(_Poorbga_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "autowavtoogg")
    public JAXBElement<BigInteger> createAutowavtoogg(BigInteger value) {
        return new JAXBElement<BigInteger>(_Autowavtoogg_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "bgasize")
    public JAXBElement<BigInteger> createBgasize(BigInteger value) {
        return new JAXBElement<BigInteger>(_Bgasize_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mp3enc_option_movie")
    public JAXBElement<String> createMp3EncOptionMovie(String value) {
        return new JAXBElement<String>(_Mp3EncOptionMovie_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "play_14")
    public JAXBElement<String> createPlay14(String value) {
        return new JAXBElement<String>(_Play14_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "lr1ir")
    public JAXBElement<BigInteger> createLr1Ir(BigInteger value) {
        return new JAXBElement<BigInteger>(_Lr1Ir_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "softwarerendering")
    public JAXBElement<BigInteger> createSoftwarerendering(BigInteger value) {
        return new JAXBElement<BigInteger>(_Softwarerendering_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "play_10")
    public JAXBElement<String> createPlay10(String value) {
        return new JAXBElement<String>(_Play10_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "random")
    public JAXBElement<BigInteger> createRandom(BigInteger value) {
        return new JAXBElement<BigInteger>(_Random_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "autoupdate")
    public JAXBElement<BigInteger> createAutoupdate(BigInteger value) {
        return new JAXBElement<BigInteger>(_Autoupdate_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "lr2ir")
    public JAXBElement<BigInteger> createLr2Ir(BigInteger value) {
        return new JAXBElement<BigInteger>(_Lr2Ir_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "maindisplay")
    public JAXBElement<BigInteger> createMaindisplay(BigInteger value) {
        return new JAXBElement<BigInteger>(_Maindisplay_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mainsleep")
    public JAXBElement<BigInteger> createMainsleep(BigInteger value) {
        return new JAXBElement<BigInteger>(_Mainsleep_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "bmssleep")
    public JAXBElement<BigInteger> createBmssleep(BigInteger value) {
        return new JAXBElement<BigInteger>(_Bmssleep_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "defaultgauge")
    public JAXBElement<BigInteger> createDefaultgauge(BigInteger value) {
        return new JAXBElement<BigInteger>(_Defaultgauge_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "defaultconnection")
    public JAXBElement<BigInteger> createDefaultconnection(BigInteger value) {
        return new JAXBElement<BigInteger>(_Defaultconnection_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "preview")
    public JAXBElement<BigInteger> createPreview(BigInteger value) {
        return new JAXBElement<BigInteger>(_Preview_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "eventmode")
    public JAXBElement<BigInteger> createEventmode(BigInteger value) {
        return new JAXBElement<BigInteger>(_Eventmode_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "soundset")
    public JAXBElement<String> createSoundset(String value) {
        return new JAXBElement<String>(_Soundset_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "disablebmsthread")
    public JAXBElement<BigInteger> createDisablebmsthread(BigInteger value) {
        return new JAXBElement<BigInteger>(_Disablebmsthread_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "lr1id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createLr1Id(String value) {
        return new JAXBElement<String>(_Lr1Id_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "bpmrange")
    public JAXBElement<BigInteger> createBpmrange(BigInteger value) {
        return new JAXBElement<BigInteger>(_Bpmrange_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "speedfirst")
    public JAXBElement<BigInteger> createSpeedfirst(BigInteger value) {
        return new JAXBElement<BigInteger>(_Speedfirst_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "movie_framerate")
    public JAXBElement<BigInteger> createMovieFramerate(BigInteger value) {
        return new JAXBElement<BigInteger>(_MovieFramerate_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "language")
    public JAXBElement<BigInteger> createLanguage(BigInteger value) {
        return new JAXBElement<BigInteger>(_Language_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sort")
    public JAXBElement<BigInteger> createSort(BigInteger value) {
        return new JAXBElement<BigInteger>(_Sort_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "searchmax")
    public JAXBElement<BigInteger> createSearchmax(BigInteger value) {
        return new JAXBElement<BigInteger>(_Searchmax_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "autokey")
    public JAXBElement<BigInteger> createAutokey(BigInteger value) {
        return new JAXBElement<BigInteger>(_Autokey_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "oggenc_option")
    public JAXBElement<String> createOggencOption(String value) {
        return new JAXBElement<String>(_OggencOption_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "shuttertype")
    public JAXBElement<BigInteger> createShuttertype(BigInteger value) {
        return new JAXBElement<BigInteger>(_Shuttertype_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "optimumlevel_5")
    public JAXBElement<BigInteger> createOptimumlevel5(BigInteger value) {
        return new JAXBElement<BigInteger>(_Optimumlevel5_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ignorekeysingle")
    public JAXBElement<BigInteger> createIgnorekeysingle(BigInteger value) {
        return new JAXBElement<BigInteger>(_Ignorekeysingle_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "optimumlevel_9")
    public JAXBElement<BigInteger> createOptimumlevel9(BigInteger value) {
        return new JAXBElement<BigInteger>(_Optimumlevel9_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fxtype_0")
    public JAXBElement<BigInteger> createFxtype0(BigInteger value) {
        return new JAXBElement<BigInteger>(_Fxtype0_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fxtype_1")
    public JAXBElement<BigInteger> createFxtype1(BigInteger value) {
        return new JAXBElement<BigInteger>(_Fxtype1_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fxtype_2")
    public JAXBElement<BigInteger> createFxtype2(BigInteger value) {
        return new JAXBElement<BigInteger>(_Fxtype2_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "optimumlevel_7")
    public JAXBElement<BigInteger> createOptimumlevel7(BigInteger value) {
        return new JAXBElement<BigInteger>(_Optimumlevel7_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "disablecurspeedchange")
    public JAXBElement<BigInteger> createDisablecurspeedchange(BigInteger value) {
        return new JAXBElement<BigInteger>(_Disablecurspeedchange_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "defaulttarget")
    public JAXBElement<BigInteger> createDefaulttarget(BigInteger value) {
        return new JAXBElement<BigInteger>(_Defaulttarget_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fxflag_0")
    public JAXBElement<BigInteger> createFxflag0(BigInteger value) {
        return new JAXBElement<BigInteger>(_Fxflag0_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "eqp4")
    public JAXBElement<BigInteger> createEqp4(BigInteger value) {
        return new JAXBElement<BigInteger>(_Eqp4_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "eqp5")
    public JAXBElement<BigInteger> createEqp5(BigInteger value) {
        return new JAXBElement<BigInteger>(_Eqp5_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "skinselect")
    public JAXBElement<String> createSkinselect(String value) {
        return new JAXBElement<String>(_Skinselect_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "eqp6")
    public JAXBElement<BigInteger> createEqp6(BigInteger value) {
        return new JAXBElement<BigInteger>(_Eqp6_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "disabledsp")
    public JAXBElement<BigInteger> createDisabledsp(BigInteger value) {
        return new JAXBElement<BigInteger>(_Disabledsp_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fxp1_2")
    public JAXBElement<BigInteger> createFxp12(BigInteger value) {
        return new JAXBElement<BigInteger>(_Fxp12_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "hsmargin")
    public JAXBElement<BigInteger> createHsmargin(BigInteger value) {
        return new JAXBElement<BigInteger>(_Hsmargin_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fxp1_1")
    public JAXBElement<BigInteger> createFxp11(BigInteger value) {
        return new JAXBElement<BigInteger>(_Fxp11_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fxp1_0")
    public JAXBElement<BigInteger> createFxp10(BigInteger value) {
        return new JAXBElement<BigInteger>(_Fxp10_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "screenmode")
    public JAXBElement<BigInteger> createScreenmode(BigInteger value) {
        return new JAXBElement<BigInteger>(_Screenmode_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "gomiscore")
    public JAXBElement<BigInteger> createGomiscore(BigInteger value) {
        return new JAXBElement<BigInteger>(_Gomiscore_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "highcolor")
    public JAXBElement<BigInteger> createHighcolor(BigInteger value) {
        return new JAXBElement<BigInteger>(_Highcolor_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "scoregraph")
    public JAXBElement<BigInteger> createScoregraph(BigInteger value) {
        return new JAXBElement<BigInteger>(_Scoregraph_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "eqp1")
    public JAXBElement<BigInteger> createEqp1(BigInteger value) {
        return new JAXBElement<BigInteger>(_Eqp1_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "eqp0")
    public JAXBElement<BigInteger> createEqp0(BigInteger value) {
        return new JAXBElement<BigInteger>(_Eqp0_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "eqp3")
    public JAXBElement<BigInteger> createEqp3(BigInteger value) {
        return new JAXBElement<BigInteger>(_Eqp3_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "eqp2")
    public JAXBElement<BigInteger> createEqp2(BigInteger value) {
        return new JAXBElement<BigInteger>(_Eqp2_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "keyconfig")
    public JAXBElement<String> createKeyconfig(String value) {
        return new JAXBElement<String>(_Keyconfig_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fxflag_1")
    public JAXBElement<BigInteger> createFxflag1(BigInteger value) {
        return new JAXBElement<BigInteger>(_Fxflag1_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fxflag_2")
    public JAXBElement<BigInteger> createFxflag2(BigInteger value) {
        return new JAXBElement<BigInteger>(_Fxflag2_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "autoreload")
    public JAXBElement<BigInteger> createAutoreload(BigInteger value) {
        return new JAXBElement<BigInteger>(_Autoreload_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mp3enc_option_normal")
    public JAXBElement<String> createMp3EncOptionNormal(String value) {
        return new JAXBElement<String>(_Mp3EncOptionNormal_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "disablesystemkey")
    public JAXBElement<BigInteger> createDisablesystemkey(BigInteger value) {
        return new JAXBElement<BigInteger>(_Disablesystemkey_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "speednext")
    public JAXBElement<BigInteger> createSpeednext(BigInteger value) {
        return new JAXBElement<BigInteger>(_Speednext_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pitchtype")
    public JAXBElement<BigInteger> createPitchtype(BigInteger value) {
        return new JAXBElement<BigInteger>(_Pitchtype_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "randomclose")
    public JAXBElement<BigInteger> createRandomclose(BigInteger value) {
        return new JAXBElement<BigInteger>(_Randomclose_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mp3_volume")
    public JAXBElement<BigInteger> createMp3Volume(BigInteger value) {
        return new JAXBElement<BigInteger>(_Mp3Volume_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "optimumlevel_14")
    public JAXBElement<BigInteger> createOptimumlevel14(BigInteger value) {
        return new JAXBElement<BigInteger>(_Optimumlevel14_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "disableleftclickexit")
    public JAXBElement<BigInteger> createDisableleftclickexit(BigInteger value) {
        return new JAXBElement<BigInteger>(_Disableleftclickexit_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "getrival")
    public JAXBElement<BigInteger> createGetrival(BigInteger value) {
        return new JAXBElement<BigInteger>(_Getrival_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "difficulty")
    public JAXBElement<BigInteger> createDifficulty(BigInteger value) {
        return new JAXBElement<BigInteger>(_Difficulty_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "disablefolderthread")
    public JAXBElement<BigInteger> createDisablefolderthread(BigInteger value) {
        return new JAXBElement<BigInteger>(_Disablefolderthread_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "optimumlevel_10")
    public JAXBElement<BigInteger> createOptimumlevel10(BigInteger value) {
        return new JAXBElement<BigInteger>(_Optimumlevel10_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "customfolder")
    public JAXBElement<BigInteger> createCustomfolder(BigInteger value) {
        return new JAXBElement<BigInteger>(_Customfolder_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ignoredp")
    public JAXBElement<BigInteger> createIgnoredp(BigInteger value) {
        return new JAXBElement<BigInteger>(_Ignoredp_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ignorekeyall")
    public JAXBElement<BigInteger> createIgnorekeyall(BigInteger value) {
        return new JAXBElement<BigInteger>(_Ignorekeyall_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "bga")
    public JAXBElement<BigInteger> createBga(BigInteger value) {
        return new JAXBElement<BigInteger>(_Bga_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "key")
    public JAXBElement<BigInteger> createKey(BigInteger value) {
        return new JAXBElement<BigInteger>(_Key_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "control")
    public JAXBElement<BigInteger> createControl(BigInteger value) {
        return new JAXBElement<BigInteger>(_Control_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "maxbpm")
    public JAXBElement<BigInteger> createMaxbpm(BigInteger value) {
        return new JAXBElement<BigInteger>(_Maxbpm_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "bufferlength")
    public JAXBElement<BigInteger> createBufferlength(BigInteger value) {
        return new JAXBElement<BigInteger>(_Bufferlength_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ignorepms")
    public JAXBElement<BigInteger> createIgnorepms(BigInteger value) {
        return new JAXBElement<BigInteger>(_Ignorepms_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "judgetime")
    public JAXBElement<BigInteger> createJudgetime(BigInteger value) {
        return new JAXBElement<BigInteger>(_Judgetime_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "numbuffers")
    public JAXBElement<BigInteger> createNumbuffers(BigInteger value) {
        return new JAXBElement<BigInteger>(_Numbuffers_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "disabledifficultyfilter")
    public JAXBElement<BigInteger> createDisabledifficultyfilter(BigInteger value) {
        return new JAXBElement<BigInteger>(_Disabledifficultyfilter_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "vsync")
    public JAXBElement<BigInteger> createVsync(BigInteger value) {
        return new JAXBElement<BigInteger>(_Vsync_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "screenexrate")
    public JAXBElement<BigInteger> createScreenexrate(BigInteger value) {
        return new JAXBElement<BigInteger>(_Screenexrate_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "shuttermargin")
    public JAXBElement<BigInteger> createShuttermargin(BigInteger value) {
        return new JAXBElement<BigInteger>(_Shuttermargin_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "oggenc_body")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createOggencBody(String value) {
        return new JAXBElement<String>(_OggencBody_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "play_7_b")
    public JAXBElement<String> createPlay7B(String value) {
        return new JAXBElement<String>(_Play7B_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "shutter")
    public JAXBElement<BigInteger> createShutter(BigInteger value) {
        return new JAXBElement<BigInteger>(_Shutter_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "play_5")
    public JAXBElement<String> createPlay5(String value) {
        return new JAXBElement<String>(_Play5_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "output")
    public JAXBElement<BigInteger> createOutput(BigInteger value) {
        return new JAXBElement<BigInteger>(_Output_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "play_9")
    public JAXBElement<String> createPlay9(String value) {
        return new JAXBElement<String>(_Play9_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "play_5_b")
    public JAXBElement<String> createPlay5B(String value) {
        return new JAXBElement<String>(_Play5B_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "play_7")
    public JAXBElement<String> createPlay7(String value) {
        return new JAXBElement<String>(_Play7_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ignorekeydouble")
    public JAXBElement<BigInteger> createIgnorekeydouble(BigInteger value) {
        return new JAXBElement<BigInteger>(_Ignorekeydouble_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "result")
    public JAXBElement<String> createResult(String value) {
        return new JAXBElement<String>(_Result_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "decide")
    public JAXBElement<String> createDecide(String value) {
        return new JAXBElement<String>(_Decide_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "hs")
    public JAXBElement<BigInteger> createHs(BigInteger value) {
        return new JAXBElement<BigInteger>(_Hs_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "bmse_body")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createBmseBody(String value) {
        return new JAXBElement<String>(_BmseBody_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "volumeflag")
    public JAXBElement<BigInteger> createVolumeflag(BigInteger value) {
        return new JAXBElement<BigInteger>(_Volumeflag_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "basespeed")
    public JAXBElement<BigInteger> createBasespeed(BigInteger value) {
        return new JAXBElement<BigInteger>(_Basespeed_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "volumebgm")
    public JAXBElement<BigInteger> createVolumebgm(BigInteger value) {
        return new JAXBElement<BigInteger>(_Volumebgm_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "movie_audio")
    public JAXBElement<BigInteger> createMovieAudio(BigInteger value) {
        return new JAXBElement<BigInteger>(_MovieAudio_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "disableimagefont")
    public JAXBElement<BigInteger> createDisableimagefont(BigInteger value) {
        return new JAXBElement<BigInteger>(_Disableimagefont_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "stage")
    public JAXBElement<BigInteger> createStage(BigInteger value) {
        return new JAXBElement<BigInteger>(_Stage_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "disablefmod")
    public JAXBElement<BigInteger> createDisablefmod(BigInteger value) {
        return new JAXBElement<BigInteger>(_Disablefmod_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createId(String value) {
        return new JAXBElement<String>(_Id_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pitchp")
    public JAXBElement<BigInteger> createPitchp(BigInteger value) {
        return new JAXBElement<BigInteger>(_Pitchp_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "autobmptopng")
    public JAXBElement<BigInteger> createAutobmptopng(BigInteger value) {
        return new JAXBElement<BigInteger>(_Autobmptopng_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "windowsize_y")
    public JAXBElement<BigInteger> createWindowsizeY(BigInteger value) {
        return new JAXBElement<BigInteger>(_WindowsizeY_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "path")
    public JAXBElement<String> createPath(String value) {
        return new JAXBElement<String>(_Path_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "windowsize_x")
    public JAXBElement<BigInteger> createWindowsizeX(BigInteger value) {
        return new JAXBElement<BigInteger>(_WindowsizeX_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "eqflag")
    public JAXBElement<BigInteger> createEqflag(BigInteger value) {
        return new JAXBElement<BigInteger>(_Eqflag_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "driver")
    public JAXBElement<BigInteger> createDriver(BigInteger value) {
        return new JAXBElement<BigInteger>(_Driver_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mp3enc_body")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createMp3EncBody(String value) {
        return new JAXBElement<String>(_Mp3EncBody_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "autofumensearch")
    public JAXBElement<BigInteger> createAutofumensearch(BigInteger value) {
        return new JAXBElement<BigInteger>(_Autofumensearch_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "newsongfolder")
    public JAXBElement<String> createNewsongfolder(String value) {
        return new JAXBElement<String>(_Newsongfolder_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "lr1pass")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createLr1Pass(String value) {
        return new JAXBElement<String>(_Lr1Pass_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "inputinterval")
    public JAXBElement<BigInteger> createInputinterval(BigInteger value) {
        return new JAXBElement<BigInteger>(_Inputinterval_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fontname")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createFontname(String value) {
        return new JAXBElement<String>(_Fontname_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pass")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPass(String value) {
        return new JAXBElement<String>(_Pass_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "titleflash")
    public JAXBElement<BigInteger> createTitleflash(BigInteger value) {
        return new JAXBElement<BigInteger>(_Titleflash_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "hsmax")
    public JAXBElement<BigInteger> createHsmax(BigInteger value) {
        return new JAXBElement<BigInteger>(_Hsmax_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "volumemaster")
    public JAXBElement<BigInteger> createVolumemaster(BigInteger value) {
        return new JAXBElement<BigInteger>(_Volumemaster_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "buttonselect")
    public JAXBElement<BigInteger> createButtonselect(BigInteger value) {
        return new JAXBElement<BigInteger>(_Buttonselect_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "minbpm")
    public JAXBElement<BigInteger> createMinbpm(BigInteger value) {
        return new JAXBElement<BigInteger>(_Minbpm_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ignore5key")
    public JAXBElement<BigInteger> createIgnore5Key(BigInteger value) {
        return new JAXBElement<BigInteger>(_Ignore5Key_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "effect")
    public JAXBElement<BigInteger> createEffect(BigInteger value) {
        return new JAXBElement<BigInteger>(_Effect_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "difficultychangetype")
    public JAXBElement<BigInteger> createDifficultychangetype(BigInteger value) {
        return new JAXBElement<BigInteger>(_Difficultychangetype_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "hptimer")
    public JAXBElement<BigInteger> createHptimer(BigInteger value) {
        return new JAXBElement<BigInteger>(_Hptimer_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "directdraw")
    public JAXBElement<BigInteger> createDirectdraw(BigInteger value) {
        return new JAXBElement<BigInteger>(_Directdraw_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "gauge")
    public JAXBElement<BigInteger> createGauge(BigInteger value) {
        return new JAXBElement<BigInteger>(_Gauge_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "target")
    public JAXBElement<BigInteger> createTarget(BigInteger value) {
        return new JAXBElement<BigInteger>(_Target_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fxp2_0")
    public JAXBElement<BigInteger> createFxp20(BigInteger value) {
        return new JAXBElement<BigInteger>(_Fxp20_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fxp2_1")
    public JAXBElement<BigInteger> createFxp21(BigInteger value) {
        return new JAXBElement<BigInteger>(_Fxp21_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "disableskinpreview")
    public JAXBElement<BigInteger> createDisableskinpreview(BigInteger value) {
        return new JAXBElement<BigInteger>(_Disableskinpreview_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fxp2_2")
    public JAXBElement<BigInteger> createFxp22(BigInteger value) {
        return new JAXBElement<BigInteger>(_Fxp22_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "hsmin")
    public JAXBElement<BigInteger> createHsmin(BigInteger value) {
        return new JAXBElement<BigInteger>(_Hsmin_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "oggdec_body")
    public JAXBElement<String> createOggdecBody(String value) {
        return new JAXBElement<String>(_OggdecBody_QNAME, String.class, null, value);
    }

}
