//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.12 at 11:34:54 AM JST 
//


package bms.player.lunaticrave2.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}hs"/>
 *         &lt;element ref="{}hstype"/>
 *         &lt;element ref="{}hsmax"/>
 *         &lt;element ref="{}hsmin"/>
 *         &lt;element ref="{}hsmargin"/>
 *         &lt;element ref="{}shutter"/>
 *         &lt;element ref="{}shuttertype"/>
 *         &lt;element ref="{}shuttermargin"/>
 *         &lt;element ref="{}gauge"/>
 *         &lt;element ref="{}random"/>
 *         &lt;element ref="{}effect"/>
 *         &lt;element ref="{}autoscratch"/>
 *         &lt;element ref="{}autokey"/>
 *         &lt;element ref="{}autojudgeadjust"/>
 *         &lt;element ref="{}judgetime"/>
 *         &lt;element ref="{}bga"/>
 *         &lt;element ref="{}bgasize"/>
 *         &lt;element ref="{}poorbga"/>
 *         &lt;element ref="{}ghost"/>
 *         &lt;element ref="{}scoregraph"/>
 *         &lt;element ref="{}target"/>
 *         &lt;element ref="{}defaulttarget"/>
 *         &lt;element ref="{}replaysave"/>
 *         &lt;element ref="{}basespeed"/>
 *         &lt;element ref="{}gomiscore"/>
 *         &lt;element ref="{}disableleftclickexit"/>
 *         &lt;element ref="{}disablecurspeedchange"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "hs",
    "hstype",
    "hsmax",
    "hsmin",
    "hsmargin",
    "shutter",
    "shuttertype",
    "shuttermargin",
    "gauge",
    "random",
    "effect",
    "autoscratch",
    "autokey",
    "autojudgeadjust",
    "judgetime",
    "bga",
    "bgasize",
    "poorbga",
    "ghost",
    "scoregraph",
    "target",
    "defaulttarget",
    "replaysave",
    "basespeed",
    "gomiscore",
    "disableleftclickexit",
    "disablecurspeedchange"
})
@XmlRootElement(name = "play")
public class Play implements Cloneable {

    @XmlElement(required = true)
    protected int hs;
    @XmlElement(required = true)
    protected int hstype;
    @XmlElement(required = true)
    protected int hsmax;
    @XmlElement(required = true)
    protected int hsmin;
    @XmlElement(required = true)
    protected int hsmargin;
    @XmlElement(required = true)
    protected int shutter;
    @XmlElement(required = true)
    protected int shuttertype;
    @XmlElement(required = true)
    protected int shuttermargin;
    @XmlElement(required = true)
    protected int gauge;
    @XmlElement(required = true)
    protected int random;
    @XmlElement(required = true)
    protected int effect;
    @XmlElement(required = true)
    protected int autoscratch;
    @XmlElement(required = true)
    protected int autokey;
    @XmlElement(required = true)
    protected int autojudgeadjust;
    @XmlElement(required = true)
    protected int judgetime;
    @XmlElement(required = true)
    protected int bga;
    @XmlElement(required = true)
    protected int bgasize;
    @XmlElement(required = true)
    protected int poorbga;
    @XmlElement(required = true)
    protected int ghost;
    @XmlElement(required = true)
    protected int scoregraph;
    @XmlElement(required = true)
    protected int target;
    @XmlElement(required = true)
    protected int defaulttarget;
    @XmlElement(required = true)
    protected int replaysave;
    @XmlElement(required = true)
    protected int basespeed;
    @XmlElement(required = true)
    protected int gomiscore;
    @XmlElement(required = true)
    protected int disableleftclickexit;
    @XmlElement(required = true)
    protected int disablecurspeedchange;

    /**
     * Gets the value of the hs property.
     * 
     * @return
     *     possible object is
     *     {@link int }
     *     
     */
    public int getHs() {
        return hs;
    }

    /**
     * Sets the value of the hs property.
     * 
     * @param value
     *     allowed object is
     *     {@link int }
     *     
     */
    public void setHs(int value) {
        this.hs = value;
    }

    /**
     * Gets the value of the hstype property.
     * 
     * @return
     *     possible object is
     *     {@link int }
     *     
     */
    public int getHstype() {
        return hstype;
    }

    /**
     * Sets the value of the hstype property.
     * 
     * @param value
     *     allowed object is
     *     {@link int }
     *     
     */
    public void setHstype(int value) {
        this.hstype = value;
    }

    /**
     * Gets the value of the hsmax property.
     * 
     * @return
     *     possible object is
     *     {@link int }
     *     
     */
    public int getHsmax() {
        return hsmax;
    }

    /**
     * Sets the value of the hsmax property.
     * 
     * @param value
     *     allowed object is
     *     {@link int }
     *     
     */
    public void setHsmax(int value) {
        this.hsmax = value;
    }

    /**
     * Gets the value of the hsmin property.
     * 
     * @return
     *     possible object is
     *     {@link int }
     *     
     */
    public int getHsmin() {
        return hsmin;
    }

    /**
     * Sets the value of the hsmin property.
     * 
     * @param value
     *     allowed object is
     *     {@link int }
     *     
     */
    public void setHsmin(int value) {
        this.hsmin = value;
    }

    /**
     * Gets the value of the hsmargin property.
     * 
     * @return
     *     possible object is
     *     {@link int }
     *     
     */
    public int getHsmargin() {
        return hsmargin;
    }

    /**
     * Sets the value of the hsmargin property.
     * 
     * @param value
     *     allowed object is
     *     {@link int }
     *     
     */
    public void setHsmargin(int value) {
        this.hsmargin = value;
    }

    /**
     * Gets the value of the shutter property.
     * 
     * @return
     *     possible object is
     *     {@link int }
     *     
     */
    public int getShutter() {
        return shutter;
    }

    /**
     * Sets the value of the shutter property.
     * 
     * @param value
     *     allowed object is
     *     {@link int }
     *     
     */
    public void setShutter(int value) {
        this.shutter = value;
    }

    /**
     * Gets the value of the shuttertype property.
     * 
     * @return
     *     possible object is
     *     {@link int }
     *     
     */
    public int getShuttertype() {
        return shuttertype;
    }

    /**
     * Sets the value of the shuttertype property.
     * 
     * @param value
     *     allowed object is
     *     {@link int }
     *     
     */
    public void setShuttertype(int value) {
        this.shuttertype = value;
    }

    /**
     * Gets the value of the shuttermargin property.
     * 
     * @return
     *     possible object is
     *     {@link int }
     *     
     */
    public int getShuttermargin() {
        return shuttermargin;
    }

    /**
     * Sets the value of the shuttermargin property.
     * 
     * @param value
     *     allowed object is
     *     {@link int }
     *     
     */
    public void setShuttermargin(int value) {
        this.shuttermargin = value;
    }

    /**
     * Gets the value of the gauge property.
     * 
     * @return
     *     possible object is
     *     {@link int }
     *     
     */
    public int getGauge() {
        return gauge;
    }

    /**
     * Sets the value of the gauge property.
     * 
     * @param value
     *     allowed object is
     *     {@link int }
     *     
     */
    public void setGauge(int value) {
        this.gauge = value;
    }

    /**
     * Gets the value of the random property.
     * 
     * @return
     *     possible object is
     *     {@link int }
     *     
     */
    public int getRandom() {
        return random;
    }

    /**
     * Sets the value of the random property.
     * 
     * @param value
     *     allowed object is
     *     {@link int }
     *     
     */
    public void setRandom(int value) {
        this.random = value;
    }

    /**
     * Gets the value of the effect property.
     * 
     * @return
     *     possible object is
     *     {@link int }
     *     
     */
    public int getEffect() {
        return effect;
    }

    /**
     * Sets the value of the effect property.
     * 
     * @param value
     *     allowed object is
     *     {@link int }
     *     
     */
    public void setEffect(int value) {
        this.effect = value;
    }

    /**
     * Gets the value of the autoscratch property.
     * 
     * @return
     *     possible object is
     *     {@link int }
     *     
     */
    public int getAutoscratch() {
        return autoscratch;
    }

    /**
     * Sets the value of the autoscratch property.
     * 
     * @param value
     *     allowed object is
     *     {@link int }
     *     
     */
    public void setAutoscratch(int value) {
        this.autoscratch = value;
    }

    /**
     * Gets the value of the autokey property.
     * 
     * @return
     *     possible object is
     *     {@link int }
     *     
     */
    public int getAutokey() {
        return autokey;
    }

    /**
     * Sets the value of the autokey property.
     * 
     * @param value
     *     allowed object is
     *     {@link int }
     *     
     */
    public void setAutokey(int value) {
        this.autokey = value;
    }

    /**
     * Gets the value of the autojudgeadjust property.
     * 
     * @return
     *     possible object is
     *     {@link int }
     *     
     */
    public int getAutojudgeadjust() {
        return autojudgeadjust;
    }

    /**
     * Sets the value of the autojudgeadjust property.
     * 
     * @param value
     *     allowed object is
     *     {@link int }
     *     
     */
    public void setAutojudgeadjust(int value) {
        this.autojudgeadjust = value;
    }

    /**
     * Gets the value of the judgetime property.
     * 
     * @return
     *     possible object is
     *     {@link int }
     *     
     */
    public int getJudgetime() {
        return judgetime;
    }

    /**
     * Sets the value of the judgetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link int }
     *     
     */
    public void setJudgetime(int value) {
        this.judgetime = value;
    }

    /**
     * Gets the value of the bga property.
     * 
     * @return
     *     possible object is
     *     {@link int }
     *     
     */
    public int getBga() {
        return bga;
    }

    /**
     * Sets the value of the bga property.
     * 
     * @param value
     *     allowed object is
     *     {@link int }
     *     
     */
    public void setBga(int value) {
        this.bga = value;
    }

    /**
     * Gets the value of the bgasize property.
     * 
     * @return
     *     possible object is
     *     {@link int }
     *     
     */
    public int getBgasize() {
        return bgasize;
    }

    /**
     * Sets the value of the bgasize property.
     * 
     * @param value
     *     allowed object is
     *     {@link int }
     *     
     */
    public void setBgasize(int value) {
        this.bgasize = value;
    }

    /**
     * Gets the value of the poorbga property.
     * 
     * @return
     *     possible object is
     *     {@link int }
     *     
     */
    public int getPoorbga() {
        return poorbga;
    }

    /**
     * Sets the value of the poorbga property.
     * 
     * @param value
     *     allowed object is
     *     {@link int }
     *     
     */
    public void setPoorbga(int value) {
        this.poorbga = value;
    }

    /**
     * Gets the value of the ghost property.
     * 
     * @return
     *     possible object is
     *     {@link int }
     *     
     */
    public int getGhost() {
        return ghost;
    }

    /**
     * Sets the value of the ghost property.
     * 
     * @param value
     *     allowed object is
     *     {@link int }
     *     
     */
    public void setGhost(int value) {
        this.ghost = value;
    }

    /**
     * Gets the value of the scoregraph property.
     * 
     * @return
     *     possible object is
     *     {@link int }
     *     
     */
    public int getScoregraph() {
        return scoregraph;
    }

    /**
     * Sets the value of the scoregraph property.
     * 
     * @param value
     *     allowed object is
     *     {@link int }
     *     
     */
    public void setScoregraph(int value) {
        this.scoregraph = value;
    }

    /**
     * Gets the value of the target property.
     * 
     * @return
     *     possible object is
     *     {@link int }
     *     
     */
    public int getTarget() {
        return target;
    }

    /**
     * Sets the value of the target property.
     * 
     * @param value
     *     allowed object is
     *     {@link int }
     *     
     */
    public void setTarget(int value) {
        this.target = value;
    }

    /**
     * Gets the value of the defaulttarget property.
     * 
     * @return
     *     possible object is
     *     {@link int }
     *     
     */
    public int getDefaulttarget() {
        return defaulttarget;
    }

    /**
     * Sets the value of the defaulttarget property.
     * 
     * @param value
     *     allowed object is
     *     {@link int }
     *     
     */
    public void setDefaulttarget(int value) {
        this.defaulttarget = value;
    }

    /**
     * Gets the value of the replaysave property.
     * 
     * @return
     *     possible object is
     *     {@link int }
     *     
     */
    public int getReplaysave() {
        return replaysave;
    }

    /**
     * Sets the value of the replaysave property.
     * 
     * @param value
     *     allowed object is
     *     {@link int }
     *     
     */
    public void setReplaysave(int value) {
        this.replaysave = value;
    }

    /**
     * Gets the value of the basespeed property.
     * 
     * @return
     *     possible object is
     *     {@link int }
     *     
     */
    public int getBasespeed() {
        return basespeed;
    }

    /**
     * Sets the value of the basespeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link int }
     *     
     */
    public void setBasespeed(int value) {
        this.basespeed = value;
    }

    /**
     * Gets the value of the gomiscore property.
     * 
     * @return
     *     possible object is
     *     {@link int }
     *     
     */
    public int getGomiscore() {
        return gomiscore;
    }

    /**
     * Sets the value of the gomiscore property.
     * 
     * @param value
     *     allowed object is
     *     {@link int }
     *     
     */
    public void setGomiscore(int value) {
        this.gomiscore = value;
    }

    /**
     * Gets the value of the disableleftclickexit property.
     * 
     * @return
     *     possible object is
     *     {@link int }
     *     
     */
    public int getDisableleftclickexit() {
        return disableleftclickexit;
    }

    /**
     * Sets the value of the disableleftclickexit property.
     * 
     * @param value
     *     allowed object is
     *     {@link int }
     *     
     */
    public void setDisableleftclickexit(int value) {
        this.disableleftclickexit = value;
    }

    /**
     * Gets the value of the disablecurspeedchange property.
     * 
     * @return
     *     possible object is
     *     {@link int }
     *     
     */
    public int getDisablecurspeedchange() {
        return disablecurspeedchange;
    }

    /**
     * Sets the value of the disablecurspeedchange property.
     * 
     * @param value
     *     allowed object is
     *     {@link int }
     *     
     */
    public void setDisablecurspeedchange(int value) {
        this.disablecurspeedchange = value;
    }

	@Override
	public Object clone() {
		try {
			return super.clone();
		} catch (CloneNotSupportedException e) {
		}
		return null;
	}
}
