//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.12 at 11:34:54 AM JST 
//


package bms.player.lunaticrave2.config;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}buttonselect"/>
 *         &lt;element ref="{}control"/>
 *         &lt;element ref="{}difficulty"/>
 *         &lt;element ref="{}difficultychangetype"/>
 *         &lt;element ref="{}disabledifficultyfilter"/>
 *         &lt;element ref="{}disablesubtitle"/>
 *         &lt;element ref="{}folderlamp"/>
 *         &lt;element ref="{}ignore5key"/>
 *         &lt;element ref="{}ignoredifficultyall"/>
 *         &lt;element ref="{}ignoredp"/>
 *         &lt;element ref="{}ignorekeyall"/>
 *         &lt;element ref="{}ignorekeydouble"/>
 *         &lt;element ref="{}ignorekeysingle"/>
 *         &lt;element ref="{}ignorepms"/>
 *         &lt;element ref="{}key"/>
 *         &lt;element ref="{}levelbarflash_5"/>
 *         &lt;element ref="{}levelbarflash_7"/>
 *         &lt;element ref="{}levelbarflash_9"/>
 *         &lt;element ref="{}preview"/>
 *         &lt;element ref="{}randomclose"/>
 *         &lt;element ref="{}searchmax"/>
 *         &lt;element ref="{}sort"/>
 *         &lt;element ref="{}speedfirst"/>
 *         &lt;element ref="{}speednext"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "select")
public class Select {

    @XmlElementRefs({
        @XmlElementRef(name = "speednext", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "disablesubtitle", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ignorekeydouble", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "key", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "folderlamp", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "searchmax", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ignoredifficultyall", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "levelbarflash_7", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "preview", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "disabledifficultyfilter", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ignoredp", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ignorekeysingle", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "randomclose", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ignorepms", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "speedfirst", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "buttonselect", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ignorekeyall", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "difficulty", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "difficultychangetype", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "levelbarflash_9", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "sort", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "control", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "levelbarflash_5", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ignore5key", type = JAXBElement.class, required = false)
    })
    @XmlMixed
    protected List<Serializable> content;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * 
     * 
     */
    public List<Serializable> getContent() {
        if (content == null) {
            content = new ArrayList<Serializable>();
        }
        return this.content;
    }

}
