//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.12 at 11:34:54 AM JST 
//


package bms.player.lunaticrave2.config;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}play_7"/>
 *         &lt;element ref="{}play_5"/>
 *         &lt;element ref="{}play_14"/>
 *         &lt;element ref="{}play_10"/>
 *         &lt;element ref="{}play_9"/>
 *         &lt;element ref="{}select"/>
 *         &lt;element ref="{}decide"/>
 *         &lt;element ref="{}result"/>
 *         &lt;element ref="{}keyconfig"/>
 *         &lt;element ref="{}skinselect"/>
 *         &lt;element ref="{}soundset"/>
 *         &lt;element ref="{}theme"/>
 *         &lt;element ref="{}play_7_b"/>
 *         &lt;element ref="{}play_5_b"/>
 *         &lt;element ref="{}play_9_b"/>
 *         &lt;element ref="{}fontname"/>
 *         &lt;element ref="{}disableimagefont"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "play7",
    "play5",
    "play14",
    "play10",
    "play9",
    "select",
    "decide",
    "result",
    "keyconfig",
    "skinselect",
    "soundset",
    "theme",
    "play7B",
    "play5B",
    "play9B",
    "fontname",
    "disableimagefont"
})
@XmlRootElement(name = "skin")
public class Skin {

    @XmlElement(name = "play_7", required = true)
    protected String play7;
    @XmlElement(name = "play_5", required = true)
    protected String play5;
    @XmlElement(name = "play_14", required = true)
    protected String play14;
    @XmlElement(name = "play_10", required = true)
    protected String play10;
    @XmlElement(name = "play_9", required = true)
    protected String play9;
    @XmlElement(required = true)
    protected Select select;
    @XmlElement(required = true)
    protected String decide;
    @XmlElement(required = true)
    protected String result;
    @XmlElement(required = true)
    protected String keyconfig;
    @XmlElement(required = true)
    protected String skinselect;
    @XmlElement(required = true)
    protected String soundset;
    @XmlElement(required = true)
    protected Theme theme;
    @XmlElement(name = "play_7_b", required = true)
    protected String play7B;
    @XmlElement(name = "play_5_b", required = true)
    protected String play5B;
    @XmlElement(name = "play_9_b", required = true)
    protected Play9B play9B;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String fontname;
    @XmlElement(required = true)
    protected BigInteger disableimagefont;

    /**
     * Gets the value of the play7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlay7() {
        return play7;
    }

    /**
     * Sets the value of the play7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlay7(String value) {
        this.play7 = value;
    }

    /**
     * Gets the value of the play5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlay5() {
        return play5;
    }

    /**
     * Sets the value of the play5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlay5(String value) {
        this.play5 = value;
    }

    /**
     * Gets the value of the play14 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlay14() {
        return play14;
    }

    /**
     * Sets the value of the play14 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlay14(String value) {
        this.play14 = value;
    }

    /**
     * Gets the value of the play10 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlay10() {
        return play10;
    }

    /**
     * Sets the value of the play10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlay10(String value) {
        this.play10 = value;
    }

    /**
     * Gets the value of the play9 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlay9() {
        return play9;
    }

    /**
     * Sets the value of the play9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlay9(String value) {
        this.play9 = value;
    }

    /**
     * Gets the value of the select property.
     * 
     * @return
     *     possible object is
     *     {@link Select }
     *     
     */
    public Select getSelect() {
        return select;
    }

    /**
     * Sets the value of the select property.
     * 
     * @param value
     *     allowed object is
     *     {@link Select }
     *     
     */
    public void setSelect(Select value) {
        this.select = value;
    }

    /**
     * Gets the value of the decide property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDecide() {
        return decide;
    }

    /**
     * Sets the value of the decide property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDecide(String value) {
        this.decide = value;
    }

    /**
     * Gets the value of the result property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResult() {
        return result;
    }

    /**
     * Sets the value of the result property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResult(String value) {
        this.result = value;
    }

    /**
     * Gets the value of the keyconfig property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyconfig() {
        return keyconfig;
    }

    /**
     * Sets the value of the keyconfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyconfig(String value) {
        this.keyconfig = value;
    }

    /**
     * Gets the value of the skinselect property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSkinselect() {
        return skinselect;
    }

    /**
     * Sets the value of the skinselect property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSkinselect(String value) {
        this.skinselect = value;
    }

    /**
     * Gets the value of the soundset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoundset() {
        return soundset;
    }

    /**
     * Sets the value of the soundset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoundset(String value) {
        this.soundset = value;
    }

    /**
     * Gets the value of the theme property.
     * 
     * @return
     *     possible object is
     *     {@link Theme }
     *     
     */
    public Theme getTheme() {
        return theme;
    }

    /**
     * Sets the value of the theme property.
     * 
     * @param value
     *     allowed object is
     *     {@link Theme }
     *     
     */
    public void setTheme(Theme value) {
        this.theme = value;
    }

    /**
     * Gets the value of the play7B property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlay7B() {
        return play7B;
    }

    /**
     * Sets the value of the play7B property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlay7B(String value) {
        this.play7B = value;
    }

    /**
     * Gets the value of the play5B property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlay5B() {
        return play5B;
    }

    /**
     * Sets the value of the play5B property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlay5B(String value) {
        this.play5B = value;
    }

    /**
     * Gets the value of the play9B property.
     * 
     * @return
     *     possible object is
     *     {@link Play9B }
     *     
     */
    public Play9B getPlay9B() {
        return play9B;
    }

    /**
     * Sets the value of the play9B property.
     * 
     * @param value
     *     allowed object is
     *     {@link Play9B }
     *     
     */
    public void setPlay9B(Play9B value) {
        this.play9B = value;
    }

    /**
     * Gets the value of the fontname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFontname() {
        return fontname;
    }

    /**
     * Sets the value of the fontname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFontname(String value) {
        this.fontname = value;
    }

    /**
     * Gets the value of the disableimagefont property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDisableimagefont() {
        return disableimagefont;
    }

    /**
     * Sets the value of the disableimagefont property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDisableimagefont(BigInteger value) {
        this.disableimagefont = value;
    }

}
