//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.12 at 11:34:54 AM JST 
//


package bms.player.lunaticrave2.config;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}screenmode"/>
 *         &lt;element ref="{}vsync"/>
 *         &lt;element ref="{}directdraw"/>
 *         &lt;element ref="{}maindisplay"/>
 *         &lt;element ref="{}highcolor"/>
 *         &lt;element ref="{}autoreload"/>
 *         &lt;element ref="{}customfolder"/>
 *         &lt;element ref="{}mainsleep"/>
 *         &lt;element ref="{}bmssleep"/>
 *         &lt;element ref="{}screenexrate"/>
 *         &lt;element ref="{}inputinterval"/>
 *         &lt;element ref="{}disablesystemkey"/>
 *         &lt;element ref="{}outputlog"/>
 *         &lt;element ref="{}thread"/>
 *         &lt;element ref="{}eventmode"/>
 *         &lt;element ref="{}disableskinpreview"/>
 *         &lt;element ref="{}newsongfolder"/>
 *         &lt;element ref="{}titleflash"/>
 *         &lt;element ref="{}hptimer"/>
 *         &lt;element ref="{}disablebmsthread"/>
 *         &lt;element ref="{}disablefolderthread"/>
 *         &lt;element ref="{}language"/>
 *         &lt;element ref="{}windowsize_x"/>
 *         &lt;element ref="{}windowsize_y"/>
 *         &lt;element ref="{}softwarerendering"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "screenmode",
    "vsync",
    "directdraw",
    "maindisplay",
    "highcolor",
    "autoreload",
    "customfolder",
    "mainsleep",
    "bmssleep",
    "screenexrate",
    "inputinterval",
    "disablesystemkey",
    "outputlog",
    "thread",
    "eventmode",
    "disableskinpreview",
    "newsongfolder",
    "titleflash",
    "hptimer",
    "disablebmsthread",
    "disablefolderthread",
    "language",
    "windowsizeX",
    "windowsizeY",
    "softwarerendering"
})
@XmlRootElement(name = "system")
public class System {

    @XmlElement(required = true)
    protected BigInteger screenmode;
    @XmlElement(required = true)
    protected BigInteger vsync;
    @XmlElement(required = true)
    protected BigInteger directdraw;
    @XmlElement(required = true)
    protected BigInteger maindisplay;
    @XmlElement(required = true)
    protected BigInteger highcolor;
    @XmlElement(required = true)
    protected BigInteger autoreload;
    @XmlElement(required = true)
    protected BigInteger customfolder;
    @XmlElement(required = true)
    protected BigInteger mainsleep;
    @XmlElement(required = true)
    protected BigInteger bmssleep;
    @XmlElement(required = true)
    protected BigInteger screenexrate;
    @XmlElement(required = true)
    protected BigInteger inputinterval;
    @XmlElement(required = true)
    protected BigInteger disablesystemkey;
    @XmlElement(required = true)
    protected BigInteger outputlog;
    @XmlElement(required = true)
    protected BigInteger thread;
    @XmlElement(required = true)
    protected BigInteger eventmode;
    @XmlElement(required = true)
    protected BigInteger disableskinpreview;
    @XmlElement(required = true)
    protected String newsongfolder;
    @XmlElement(required = true)
    protected BigInteger titleflash;
    @XmlElement(required = true)
    protected BigInteger hptimer;
    @XmlElement(required = true)
    protected BigInteger disablebmsthread;
    @XmlElement(required = true)
    protected BigInteger disablefolderthread;
    @XmlElement(required = true)
    protected BigInteger language;
    @XmlElement(name = "windowsize_x", required = true)
    protected BigInteger windowsizeX;
    @XmlElement(name = "windowsize_y", required = true)
    protected BigInteger windowsizeY;
    @XmlElement(required = true)
    protected BigInteger softwarerendering;

    /**
     * Gets the value of the screenmode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getScreenmode() {
        return screenmode;
    }

    /**
     * Sets the value of the screenmode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setScreenmode(BigInteger value) {
        this.screenmode = value;
    }

    /**
     * Gets the value of the vsync property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVsync() {
        return vsync;
    }

    /**
     * Sets the value of the vsync property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVsync(BigInteger value) {
        this.vsync = value;
    }

    /**
     * Gets the value of the directdraw property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDirectdraw() {
        return directdraw;
    }

    /**
     * Sets the value of the directdraw property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDirectdraw(BigInteger value) {
        this.directdraw = value;
    }

    /**
     * Gets the value of the maindisplay property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaindisplay() {
        return maindisplay;
    }

    /**
     * Sets the value of the maindisplay property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaindisplay(BigInteger value) {
        this.maindisplay = value;
    }

    /**
     * Gets the value of the highcolor property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHighcolor() {
        return highcolor;
    }

    /**
     * Sets the value of the highcolor property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHighcolor(BigInteger value) {
        this.highcolor = value;
    }

    /**
     * Gets the value of the autoreload property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAutoreload() {
        return autoreload;
    }

    /**
     * Sets the value of the autoreload property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAutoreload(BigInteger value) {
        this.autoreload = value;
    }

    /**
     * Gets the value of the customfolder property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCustomfolder() {
        return customfolder;
    }

    /**
     * Sets the value of the customfolder property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCustomfolder(BigInteger value) {
        this.customfolder = value;
    }

    /**
     * Gets the value of the mainsleep property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMainsleep() {
        return mainsleep;
    }

    /**
     * Sets the value of the mainsleep property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMainsleep(BigInteger value) {
        this.mainsleep = value;
    }

    /**
     * Gets the value of the bmssleep property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBmssleep() {
        return bmssleep;
    }

    /**
     * Sets the value of the bmssleep property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBmssleep(BigInteger value) {
        this.bmssleep = value;
    }

    /**
     * Gets the value of the screenexrate property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getScreenexrate() {
        return screenexrate;
    }

    /**
     * Sets the value of the screenexrate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setScreenexrate(BigInteger value) {
        this.screenexrate = value;
    }

    /**
     * Gets the value of the inputinterval property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getInputinterval() {
        return inputinterval;
    }

    /**
     * Sets the value of the inputinterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setInputinterval(BigInteger value) {
        this.inputinterval = value;
    }

    /**
     * Gets the value of the disablesystemkey property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDisablesystemkey() {
        return disablesystemkey;
    }

    /**
     * Sets the value of the disablesystemkey property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDisablesystemkey(BigInteger value) {
        this.disablesystemkey = value;
    }

    /**
     * Gets the value of the outputlog property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOutputlog() {
        return outputlog;
    }

    /**
     * Sets the value of the outputlog property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOutputlog(BigInteger value) {
        this.outputlog = value;
    }

    /**
     * Gets the value of the thread property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getThread() {
        return thread;
    }

    /**
     * Sets the value of the thread property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setThread(BigInteger value) {
        this.thread = value;
    }

    /**
     * Gets the value of the eventmode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEventmode() {
        return eventmode;
    }

    /**
     * Sets the value of the eventmode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEventmode(BigInteger value) {
        this.eventmode = value;
    }

    /**
     * Gets the value of the disableskinpreview property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDisableskinpreview() {
        return disableskinpreview;
    }

    /**
     * Sets the value of the disableskinpreview property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDisableskinpreview(BigInteger value) {
        this.disableskinpreview = value;
    }

    /**
     * Gets the value of the newsongfolder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewsongfolder() {
        return newsongfolder;
    }

    /**
     * Sets the value of the newsongfolder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewsongfolder(String value) {
        this.newsongfolder = value;
    }

    /**
     * Gets the value of the titleflash property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTitleflash() {
        return titleflash;
    }

    /**
     * Sets the value of the titleflash property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTitleflash(BigInteger value) {
        this.titleflash = value;
    }

    /**
     * Gets the value of the hptimer property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHptimer() {
        return hptimer;
    }

    /**
     * Sets the value of the hptimer property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHptimer(BigInteger value) {
        this.hptimer = value;
    }

    /**
     * Gets the value of the disablebmsthread property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDisablebmsthread() {
        return disablebmsthread;
    }

    /**
     * Sets the value of the disablebmsthread property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDisablebmsthread(BigInteger value) {
        this.disablebmsthread = value;
    }

    /**
     * Gets the value of the disablefolderthread property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDisablefolderthread() {
        return disablefolderthread;
    }

    /**
     * Sets the value of the disablefolderthread property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDisablefolderthread(BigInteger value) {
        this.disablefolderthread = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLanguage(BigInteger value) {
        this.language = value;
    }

    /**
     * Gets the value of the windowsizeX property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWindowsizeX() {
        return windowsizeX;
    }

    /**
     * Sets the value of the windowsizeX property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWindowsizeX(BigInteger value) {
        this.windowsizeX = value;
    }

    /**
     * Gets the value of the windowsizeY property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWindowsizeY() {
        return windowsizeY;
    }

    /**
     * Sets the value of the windowsizeY property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWindowsizeY(BigInteger value) {
        this.windowsizeY = value;
    }

    /**
     * Gets the value of the softwarerendering property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSoftwarerendering() {
        return softwarerendering;
    }

    /**
     * Sets the value of the softwarerendering property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSoftwarerendering(BigInteger value) {
        this.softwarerendering = value;
    }

}
