//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.12 at 11:34:54 AM JST 
//


package bms.player.lunaticrave2.config;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}bmse_body"/>
 *         &lt;element ref="{}bmse_option"/>
 *         &lt;element ref="{}movie_audio"/>
 *         &lt;element ref="{}movie_framerate"/>
 *         &lt;element ref="{}mp3_volume"/>
 *         &lt;element ref="{}mp3enc_body"/>
 *         &lt;element ref="{}mp3enc_option_movie"/>
 *         &lt;element ref="{}mp3enc_option_normal"/>
 *         &lt;element ref="{}oggdec_body"/>
 *         &lt;element ref="{}oggdec_option"/>
 *         &lt;element ref="{}oggenc_body"/>
 *         &lt;element ref="{}oggenc_option"/>
 *         &lt;element ref="{}autowavtoogg"/>
 *         &lt;element ref="{}autobmptopng"/>
 *         &lt;element ref="{}autofumensearch"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bmseBody",
    "bmseOption",
    "movieAudio",
    "movieFramerate",
    "mp3Volume",
    "mp3EncBody",
    "mp3EncOptionMovie",
    "mp3EncOptionNormal",
    "oggdecBody",
    "oggdecOption",
    "oggencBody",
    "oggencOption",
    "autowavtoogg",
    "autobmptopng",
    "autofumensearch"
})
@XmlRootElement(name = "tools")
public class Tools {

    @XmlElement(name = "bmse_body", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String bmseBody;
    @XmlElement(name = "bmse_option", required = true)
    protected BmseOption bmseOption;
    @XmlElement(name = "movie_audio", required = true)
    protected BigInteger movieAudio;
    @XmlElement(name = "movie_framerate", required = true)
    protected BigInteger movieFramerate;
    @XmlElement(name = "mp3_volume", required = true)
    protected BigInteger mp3Volume;
    @XmlElement(name = "mp3enc_body", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String mp3EncBody;
    @XmlElement(name = "mp3enc_option_movie", required = true)
    protected String mp3EncOptionMovie;
    @XmlElement(name = "mp3enc_option_normal", required = true)
    protected String mp3EncOptionNormal;
    @XmlElement(name = "oggdec_body", required = true)
    protected String oggdecBody;
    @XmlElement(name = "oggdec_option", required = true)
    protected OggdecOption oggdecOption;
    @XmlElement(name = "oggenc_body", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String oggencBody;
    @XmlElement(name = "oggenc_option", required = true)
    protected String oggencOption;
    @XmlElement(required = true)
    protected BigInteger autowavtoogg;
    @XmlElement(required = true)
    protected BigInteger autobmptopng;
    @XmlElement(required = true)
    protected BigInteger autofumensearch;

    /**
     * Gets the value of the bmseBody property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBmseBody() {
        return bmseBody;
    }

    /**
     * Sets the value of the bmseBody property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBmseBody(String value) {
        this.bmseBody = value;
    }

    /**
     * Gets the value of the bmseOption property.
     * 
     * @return
     *     possible object is
     *     {@link BmseOption }
     *     
     */
    public BmseOption getBmseOption() {
        return bmseOption;
    }

    /**
     * Sets the value of the bmseOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link BmseOption }
     *     
     */
    public void setBmseOption(BmseOption value) {
        this.bmseOption = value;
    }

    /**
     * Gets the value of the movieAudio property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMovieAudio() {
        return movieAudio;
    }

    /**
     * Sets the value of the movieAudio property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMovieAudio(BigInteger value) {
        this.movieAudio = value;
    }

    /**
     * Gets the value of the movieFramerate property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMovieFramerate() {
        return movieFramerate;
    }

    /**
     * Sets the value of the movieFramerate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMovieFramerate(BigInteger value) {
        this.movieFramerate = value;
    }

    /**
     * Gets the value of the mp3Volume property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMp3Volume() {
        return mp3Volume;
    }

    /**
     * Sets the value of the mp3Volume property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMp3Volume(BigInteger value) {
        this.mp3Volume = value;
    }

    /**
     * Gets the value of the mp3EncBody property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMp3EncBody() {
        return mp3EncBody;
    }

    /**
     * Sets the value of the mp3EncBody property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMp3EncBody(String value) {
        this.mp3EncBody = value;
    }

    /**
     * Gets the value of the mp3EncOptionMovie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMp3EncOptionMovie() {
        return mp3EncOptionMovie;
    }

    /**
     * Sets the value of the mp3EncOptionMovie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMp3EncOptionMovie(String value) {
        this.mp3EncOptionMovie = value;
    }

    /**
     * Gets the value of the mp3EncOptionNormal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMp3EncOptionNormal() {
        return mp3EncOptionNormal;
    }

    /**
     * Sets the value of the mp3EncOptionNormal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMp3EncOptionNormal(String value) {
        this.mp3EncOptionNormal = value;
    }

    /**
     * Gets the value of the oggdecBody property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOggdecBody() {
        return oggdecBody;
    }

    /**
     * Sets the value of the oggdecBody property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOggdecBody(String value) {
        this.oggdecBody = value;
    }

    /**
     * Gets the value of the oggdecOption property.
     * 
     * @return
     *     possible object is
     *     {@link OggdecOption }
     *     
     */
    public OggdecOption getOggdecOption() {
        return oggdecOption;
    }

    /**
     * Sets the value of the oggdecOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link OggdecOption }
     *     
     */
    public void setOggdecOption(OggdecOption value) {
        this.oggdecOption = value;
    }

    /**
     * Gets the value of the oggencBody property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOggencBody() {
        return oggencBody;
    }

    /**
     * Sets the value of the oggencBody property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOggencBody(String value) {
        this.oggencBody = value;
    }

    /**
     * Gets the value of the oggencOption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOggencOption() {
        return oggencOption;
    }

    /**
     * Sets the value of the oggencOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOggencOption(String value) {
        this.oggencOption = value;
    }

    /**
     * Gets the value of the autowavtoogg property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAutowavtoogg() {
        return autowavtoogg;
    }

    /**
     * Sets the value of the autowavtoogg property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAutowavtoogg(BigInteger value) {
        this.autowavtoogg = value;
    }

    /**
     * Gets the value of the autobmptopng property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAutobmptopng() {
        return autobmptopng;
    }

    /**
     * Sets the value of the autobmptopng property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAutobmptopng(BigInteger value) {
        this.autobmptopng = value;
    }

    /**
     * Gets the value of the autofumensearch property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAutofumensearch() {
        return autofumensearch;
    }

    /**
     * Sets the value of the autofumensearch property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAutofumensearch(BigInteger value) {
        this.autofumensearch = value;
    }

}
