package bms.player.beatoraja.input;

public enum KeyCommand {

	SHOW_FPS,
	UPDATE_FOLDER,
	OPEN_EXPLORER,
	SWITCH_SCREEN_MODE,
	SAVE_SCREENSHOT,
	POST_TWITTER,
	ADD_FAVORITE_SONG,
	ADD_FAVORITE_CHART,
	AUTOPLAY_FOLDER,
	OPEN_IR,
	OPEN_SKIN_CONFIGURATION,
}
